apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: nicolas-gomez
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: nicolasg1911/web-app:0.1
          ports:
            - containerPort: 80
      readinessProbe:
        httpGet:
          path: /health
          port: 80
