apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-app.fullname" . }}
  namespace: nicolas-gomez
  labels:
    {{- include "web-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
  selector:
      app: web-app
